### ISSUE TITLE
magpack_pack下标问题

### ISSUE THREAD

**Issue by yanpeipan** [msgpack/msgpack-php#42]
```php
msgpack_pack(array(1007, 'code' => 400));
msgpack_pack(array(1007, 400));
```

当用lua`msgpack.decode`解码时， 会得到`table{[0]=1007, ['code']=400}` , `{1007, 400}`
因为lua数组下标从1开始，期望结果应该是 `table{1007, ['code']=400}`

**Comment by joeyhub** [comment]
PHP hashes are a mess without proper separation between a standard array and map (they are hybridised) but on the other hand LUA is weak for starting arrays at 1 rather than the standard of 0.

This looks a bit more like an issue in the way LUA decodes rather than in PHP or simply an incompatibility with the languages. If you fix this for php it will be broken in LUA so it should be "wontfix".

Best practice means you should avoid mixing maps and arrays anyway.

    [1007,'code'=>400]

Is bad practice.

**Comment by laruence** [comment]
wontfix as @joeyhub commented
