### ISSUE TITLE
load error when no "session" ext

### ISSUE THREAD

**Issue by zhengkai** [msgpack/msgpack-php#79]
php 7.0.2
php-msgpack 2.0.0

php configure & make with `--enable-session=shared`

if load session and msgpack, everything is well:

    [PHP]
    extension=session.so
    extension=msgpack.so

when I disable session:

    [PHP]
    ; extension=session.so
    extension=msgpack.so

It takes error 

    [01-Feb-2016 08:11:35 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/extensions/no-debug-non-zts-20151012/msgpack.so' - /usr/lib/php/extensions/no-debug-non-zts-20151012/msgpack.so: undefined symbol: ps_globals in Unknown on line 0

**Comment by Sean-Der** [comment]
Hi @zhengkai 

When msgpack is compiled it adds/removes code depending on if you want [session support](https://github.com/msgpack/msgpack-php/blob/bc11c9cc7f3369dc3e0f62ad6b8a687499eb9740/msgpack.c#L12).

So if you add session support, and then remove it you will get errors because the compiled object expects these symbols. 

Feel free to reopen this issue if I didn't understand properly!

**Comment by zhengkai** [comment]
Hi @Sean-Der 

Maybe it can check if session-ext exists when php start ?
Or at the least, add a switch to disable session-ext depending, not only auto detect?
(sorry my english is poor, chinese now)

@laruence 
我是觉得可以有更完善的检测，我知道 session 可以用到 msgpack，他们有个相互依赖的关系，但我希望 php 开始运行（cli 或者 fpm）并加载模块时，你不需要额外做什么，也不会有报错，一切都可以正常过去

因为 session 跟 msgpack 的关系就是，msgpack 加载时跟 session 打个招呼说你也可以用 msgpack 做序列化，是 session 可以用到 msgpack 而不是 msgpack 要用到 session

本来 session 是否存在并不影响 msgpack 本身的使用，但是现在单独加载 msgpack 会报错

而且我在 php configure 时 --enable-session=shared ，如果 php.ini 里没写 extension=session.so ，是不会加载的，但 msgpack 在编译时应该是看到只要有 --enable-session 就会默认二者有关联？所以至少 msgpack 里应该有个编译参数来控制吧，不然岂不是为了 msgpack 我得 build 两次 php ？
